// Generated by https://quicktype.io
/* {
  "data": {
    "_table": {
      "_base": {
        "_airtable": {},
        "_id": "appaYwKFsyvOAQqmh"
      },
      "id": null,
      "name": "dogs"
    },
    "id": "recGW7iPQw94jW8Rm",
    "_rawJson": {
      "id": "recGW7iPQw94jW8Rm",
      "fields": {
        "Family": [
          "rec8uwTylS1kUIUrN"
        ],
        "Color": "black",
        "For Sale?": true,
        "Parents": [
          "rec3sTZgKGEXYyte1",
          "recL0AMMDjJZ7KyjW"
        ],
        "Name": "Beth",
        "Weigh-Ins": [
          "recrHYTqeKeX6YkEx",
          "recHvgKYssc1lZ7u1"
        ],
        "Gender": "FEMALE",
        "Breed": [
          "recP6p0554BlyGgMz"
        ],
        "Dad": [
          "Jake"
        ],
        "Mom": [
          "Maci Rae"
        ],
        "Birthday Lookup": [
          "2021-12-14"
        ],
        "Birthday": [
          "2021-12-14"
        ],
        "Record ID": "recGW7iPQw94jW8Rm",
        "Take Home Days Remaining": "1",
        "Take-Home Date": "2022-02-08",
        "Breed Name": [
          "Bernedoodle"
        ],
        "Request Form Link": "https://airtable.com/shrJEjrCA8u45yzYU?prefill_Dog=recGW7iPQw94jW8Rm&prefill_Date=2022-02-07T00%3A00%3A00.000Z",
        "Dad Breed Name": [
          "Bernese Mountain Dog"
        ],
        "Mom Breed Name": [
          "Standard Poodle"
        ]
      },
      "createdTime": "2022-01-26T15:27:05.000Z"
    },
    "fields": {
      "Family": [
        "rec8uwTylS1kUIUrN"
      ],
      "Color": "black",
      "For Sale?": true,
      "Parents": [
        "rec3sTZgKGEXYyte1",
        "recL0AMMDjJZ7KyjW"
      ],
      "Name": "Beth",
      "Weigh-Ins": [
        "recrHYTqeKeX6YkEx",
        "recHvgKYssc1lZ7u1"
      ],
      "Gender": "FEMALE",
      "Breed": [
        "recP6p0554BlyGgMz"
      ],
      "Dad": [
        "Jake"
      ],
      "Mom": [
        "Maci Rae"
      ],
      "Birthday Lookup": [
        "2021-12-14"
      ],
      "Birthday": [
        "2021-12-14"
      ],
      "Record ID": "recGW7iPQw94jW8Rm",
      "Take Home Days Remaining": "1",
      "Take-Home Date": "2022-02-08",
      "Breed Name": [
        "Bernedoodle"
      ],
      "Request Form Link": "https://airtable.com/shrJEjrCA8u45yzYU?prefill_Dog=recGW7iPQw94jW8Rm&prefill_Date=2022-02-07T00%3A00%3A00.000Z",
      "Dad Breed Name": [
        "Bernese Mountain Dog"
      ],
      "Mom Breed Name": [
        "Standard Poodle"
      ]
    }
  }
} */

export interface RawDog {
  _table: Table;
  id: string;
  _rawJson: RawJSON;
  fields: Fields;
}

interface RawJSON {
  id: string;
  fields: Fields;
  createdTime: string;
}

interface Fields {
  Family: string[];
  Color: string;
  'For Sale?': boolean;
  Parents: string[];
  Name: string;
  'Weigh-Ins': string[];
  Gender: string;
  Breed: string[];
  Dad: string[];
  Mom: string[];
  'Birthday Lookup': string[];
  Birthday: string[];
  'Record ID': string;
  'Take Home Days Remaining': string;
  'Take-Home Date': string;
  'Breed Name': string[];
  'Request Form Link': string;
  'Dad Breed Name': string[];
  'Mom Breed Name': string[];
}

interface Table {
  _base: Base;
  id: null;
  name: string;
}

interface Base {
  _airtable: {};
  _id: string;
}

export interface Dog {
  family?: string[];
  roles?: string[];
  masterS?: string[];
  color?: string;
  parents?: string[];
  familes?: string[];
  embarkId?: string;
  name?: string;
  gender?: string;
  breed?: string[];
  embarkUrl?: string;
  dad?: string[];
  mom?: string[];
  birthdayLookup?: Date[];
  birthday?: Date[] | Date;
  age?: AgeClass | string;
  recordId?: string;
  takeHomeDaysRemaining?: AgeMonthsClass | number;
  takeHomeDate?: AgeClass | Date;
  ageYears?: string;
  ageMonths?: AgeMonthsClass | number;
  ageWeeks?: AgeMonthsClass | number;
  avatar?: Avatar[];
  available?: boolean;
  weighIns?: string[];
  birthdayEntry?: Date;
}

export interface AgeClass {
  error?: string;
}

export interface AgeMonthsClass {
  specialValue?: string;
}

export interface Avatar {
  id?: string;
  width?: number;
  height?: number;
  url?: string;
  filename?: string;
  size?: number;
  type?: string;
  thumbnails?: Thumbnails;
}

export interface Thumbnails {
  small?: Full;
  large?: Full;
  full?: Full;
}

export interface Full {
  url?: string;
  width?: number;
  height?: number;
}
